# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 734849b2b0dc87bbc517b5c345b5365dc661dc23412e836bcaeae6ce135352e000a47de52d062130fd266e4a17747dacc22e0c67cedab4ff19c12e0cd316ef4c

test:
  secret_key_base: 44df6a21c9ee286226536f64c6d33a8370bc2f72fb9a53c57038055d658da4cbcfdcb622264e43007bd7405c55d122ef2ef0ea653d8cb74f076d94cceb98d1b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
